module.exports = [
  {
    id: 1,
    bio: 'Bryn enjoys cool music, a cool breeze, and cool drinks. He dislikes hot drinks, hot breath, and hot weather.',
    breed: 'German Shepard / Rough Collie',
    img: 'http://files.slack.com/files-tmb/T044YC3BH-F01ABC4CDMW-c811a031b6/img_8582_720.jpg',
    name: 'Bryn',
    petType: 'dog',
    weight: 55,
  },
  {
    id: 2,
    bio: 'Loves people - hates other cats. When not following her family around, enjoys sitting in bags, boxes, frying pans - whatever.',
    breed: 'Dilute Tabby',
    img: 'http://slack-imgs.com/?c=1&o1=ro&url=https%3A%2F%2Flh3.googleusercontent.com%2FOruQO3z2SuBgs87hhj_gHnCTRn3e53u1t4puCqmIcTrtuvDz8cP3R51RnapQFHetLCAirTEd-IrAwph_eYU9r9wVRdTK2IfPn8DxQKWdGb_2T63zOdi0POK14I0AD4hqZPIIMdAbtA',
    name: 'Lyra',
    petType: 'cat',
    weight: 13,
  },
  {
    id: 3,
    bio: 'Sophie likes sleeping, screaming at the top of her lungs, and sleeping more. She dislikes her new cat-sister, and long car rides.',
    breed: 'Domestic Short Hair',
    img: 'http://files.slack.com/files-pri/T044YC3BH-F019GMRUGMU/attach56010_20190908_192057.jpg',
    name: 'Sophie',
    petType: 'cat',
    weight: 8,
  },
  {
    id: 4,
    bio: 'Rosie is super chill, loves her walks, & dislikes squirrels. She tries to catch em but they’re to fast for her but nonetheless she remains persistent.',
    breed: 'Black Lab',
    img: 'http://files.slack.com/files-pri/T044YC3BH-F0199DCJ8KZ/be19006b-27ca-406c-b661-4664775d1fee.jpg',
    name: 'Rosie',
    petType: 'dog',
    weight: 85,
  },
  {
    id: 5,
    bio: ' Ada loves her dog friends, cheese, green beans, walks to the park, and playing with balls. She doesn’t like shrimp, strangers, being home alone, or ear drops.',
    breed: 'Pit lab mix',
    img: 'http://files.slack.com/files-pri/T044YC3BH-F019RKTL57D/image_from_ios.jpg',
    name: 'Ada',
    petType: 'dog',
    weight: 62,
  },
];
